name = "Wantsum"
license = "MIT"
licenselink = "https://github.com/alexandrevicenzi/soho/blob/master/LICENSE.md"
description = "A minimalist and mobile first theme for Hugo"
tags = ["blog", "responsive", "light", "dark", "minimal"]
features = ["blog", "seo", "responsive", "mobile"]
min_version = "0.54.0"

[author]
    name = "bcc"
    homepage = "https://spod.cx"

[original]
    name = "alexandrevicenzi"
    homepage = "https://alxd.dev"
